// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZDpZiaCK2XLsxbLbsyu-IJ4InM9Ti0hA',
    appId: '1:177945112143:web:765f06fa1880463414043a',
    messagingSenderId: '177945112143',
    projectId: 'vibeup-636a2',
    authDomain: 'vibeup-636a2.firebaseapp.com',
    storageBucket: 'vibeup-636a2.firebasestorage.app',
    measurementId: 'G-VML898VF2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqYV5gJfXSmr7JhknNIMSN9bBPY3I49Cc',
    appId: '1:177945112143:android:5acbc06d7c1c5f2814043a',
    messagingSenderId: '177945112143',
    projectId: 'vibeup-636a2',
    storageBucket: 'vibeup-636a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-K3wDPMMMkVE1FQFx03UmChn_3MvuL8s',
    appId: '1:177945112143:ios:02d2848434f26b1614043a',
    messagingSenderId: '177945112143',
    projectId: 'vibeup-636a2',
    storageBucket: 'vibeup-636a2.firebasestorage.app',
    iosBundleId: 'com.example.vibeup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-K3wDPMMMkVE1FQFx03UmChn_3MvuL8s',
    appId: '1:177945112143:ios:02d2848434f26b1614043a',
    messagingSenderId: '177945112143',
    projectId: 'vibeup-636a2',
    storageBucket: 'vibeup-636a2.firebasestorage.app',
    iosBundleId: 'com.example.vibeup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZDpZiaCK2XLsxbLbsyu-IJ4InM9Ti0hA',
    appId: '1:177945112143:web:96f376e3d55c078514043a',
    messagingSenderId: '177945112143',
    projectId: 'vibeup-636a2',
    authDomain: 'vibeup-636a2.firebaseapp.com',
    storageBucket: 'vibeup-636a2.firebasestorage.app',
    measurementId: 'G-5NGC1ZGK0W',
  );
}
