// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLxblQI4HMEFMFDJ4l9MhA_K7qRPGlPWA',
    appId: '1:615139315784:web:2c9fc1ccd2eae35a77087d',
    messagingSenderId: '615139315784',
    projectId: 'vibeup-de0fc',
    authDomain: 'vibeup-de0fc.firebaseapp.com',
    storageBucket: 'vibeup-de0fc.firebasestorage.app',
    measurementId: 'G-T6SSQWJWZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6UDxpHUTWGo-klBJmmLPnZ9LvqSb3jBM',
    appId: '1:615139315784:android:b2912d6b20759dce77087d',
    messagingSenderId: '615139315784',
    projectId: 'vibeup-de0fc',
    storageBucket: 'vibeup-de0fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Wpd06cmaKCx5u0BeSCIr6pYdbBLnvg0',
    appId: '1:615139315784:ios:aff6ccec942e963477087d',
    messagingSenderId: '615139315784',
    projectId: 'vibeup-de0fc',
    storageBucket: 'vibeup-de0fc.firebasestorage.app',
    iosBundleId: 'com.example.vibeup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Wpd06cmaKCx5u0BeSCIr6pYdbBLnvg0',
    appId: '1:615139315784:ios:aff6ccec942e963477087d',
    messagingSenderId: '615139315784',
    projectId: 'vibeup-de0fc',
    storageBucket: 'vibeup-de0fc.firebasestorage.app',
    iosBundleId: 'com.example.vibeup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLxblQI4HMEFMFDJ4l9MhA_K7qRPGlPWA',
    appId: '1:615139315784:web:dbf8c57cee07a05877087d',
    messagingSenderId: '615139315784',
    projectId: 'vibeup-de0fc',
    authDomain: 'vibeup-de0fc.firebaseapp.com',
    storageBucket: 'vibeup-de0fc.firebasestorage.app',
    measurementId: 'G-GKL7HGY44K',
  );

}